version: '3.9'

services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=userDoBanco
      - POSTGRES_PASSWORD=passDoBanco
      - POSTGRES_DB=customerApi
    ports:
      - '5432:5432'

  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"